stages:
  - test
  - publish

test:
  stage: test
  image: python:3.8
  cache:
    paths:
      - .venv/
      - .cache/pip
  before_script:
    - python -V
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
  script:
    - poetry run pytest

publish:
  stage: publish
  image: python:3.8
  tags:
    - esisogr87
  cache:
    paths:
      - .venv/
      - .cache/pip
  before_script:
    - python -V
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry config repositories.devpi $PYPI_REPOSITORY
  script:
    - poetry publish --build -r devpi -u $PYPI_USERNAME -p $PYPI_PASSWORD
    - ./generate_docs.sh
  rules:
    - if: $CI_COMMIT_TAG
