stages:
  - test
  - publish
  
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key:
    files:
      - poetry.lock
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .venv
    - .cache/pip

test:
  stage: test
  image: python:3.8
  tags:
    - esisogr87
  before_script:
    - python -V
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-root
  script:
    - poetry run pytest

publish:
  stage: publish
  image: python:3.8
  tags:
    - esisogr87
  before_script:
    - python -V
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry config repositories.devpi $PYPI_REPOSITORY
  script:
    - poetry publish --build -r devpi -u $PYPI_USERNAME -p $PYPI_PASSWORD
    - ./generate_docs.sh
  rules:
    - if: $CI_COMMIT_TAG
