# coding: utf-8

# flake8: noqa

"""
    Location

    Location can verify if the specified user is within the given area  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from location_client.api_client import ApiClient

# import Configuration
from location_client.configuration import Configuration

# import exceptions
from location_client.exceptions import OpenApiException
from location_client.exceptions import ApiAttributeError
from location_client.exceptions import ApiTypeError
from location_client.exceptions import ApiValueError
from location_client.exceptions import ApiKeyError
from location_client.exceptions import ApiException
