# coding: utf-8

"""
    Slice

    Slice management, creating and deleting network slices.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import slice_client
from slice_client.model.area_of_service import AreaOfService
from slice_client import configuration


class TestAreaOfService(unittest.TestCase):
    """AreaOfService unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
