# coding: utf-8

"""
    Location

    Location can verify if the specified user is within the given area  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from location_client.paths.get.get import LocationQueryGetGet
from location_client.paths.verify.get import VerifyLocationVerifyGet


class LocationApi(
    LocationQueryGetGet,
    VerifyLocationVerifyGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
