# coding: utf-8

"""
    Location

    Location can verify if the specified user is within the given area  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import location_client
from location_client.model.civic_address import CivicAddress
from location_client import configuration


class TestCivicAddress(unittest.TestCase):
    """CivicAddress unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
