# coding: utf-8

"""
    QoS

    QoS manages communication bandwidth for a given device.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from qos_client.paths.sessions.post import CreateSession
from qos_client.paths.sessions_session_id.delete import DeleteSession
from qos_client.paths.sessions.get import GetAllSessions
from qos_client.paths.sessions_session_id.get import GetSession


class DefaultApi(
    CreateSession,
    DeleteSession,
    GetAllSessions,
    GetSession,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
