# coding: utf-8

"""
    QoS

    QoS manages communication bandwidth for a given device.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from qos_client.paths.sessions.post import CreateQosSessionsPost
from qos_client.paths.sessions_resource_id.delete import DeleteQosSessionsResourceIdDelete
from qos_client.paths.sessions.get import GetAllQosSessionsGet
from qos_client.paths.sessions_resource_id.get import GetQosSessionsResourceIdGet


class QosApi(
    CreateQosSessionsPost,
    DeleteQosSessionsResourceIdDelete,
    GetAllQosSessionsGet,
    GetQosSessionsResourceIdGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
