# coding: utf-8

"""
    QoS on Demand

    Manage QoS sessions for users on demand.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from qos_client.paths.sessions.post import CreateSession
from qos_client.paths.sessions_id.delete import DeleteSession
from qos_client.paths.sessions.get import GetAllSessions
from qos_client.paths.sessions_session_id.get import GetSession


class SessionsApi(
    CreateSession,
    DeleteSession,
    GetAllSessions,
    GetSession,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
