# coding: utf-8

# flake8: noqa

"""
    Slice

    Slice management, creating and deleting network slices.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from slice_client.api_client import ApiClient

# import Configuration
from slice_client.configuration import Configuration

# import exceptions
from slice_client.exceptions import OpenApiException
from slice_client.exceptions import ApiAttributeError
from slice_client.exceptions import ApiTypeError
from slice_client.exceptions import ApiValueError
from slice_client.exceptions import ApiKeyError
from slice_client.exceptions import ApiException
