# coding: utf-8

# flake8: noqa

"""
    QoS

    QoS manages communication bandwidth for a given device.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from qos_client.api_client import ApiClient

# import Configuration
from qos_client.configuration import Configuration

# import exceptions
from qos_client.exceptions import OpenApiException
from qos_client.exceptions import ApiAttributeError
from qos_client.exceptions import ApiTypeError
from qos_client.exceptions import ApiValueError
from qos_client.exceptions import ApiKeyError
from qos_client.exceptions import ApiException
