# coding: utf-8

"""
    Device Status

    Device Status can provide updates on the device's connectivity state  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import devicestatus_client
from devicestatus_client.model.device_ipv4_addr import DeviceIpv4Addr
from devicestatus_client import configuration


class TestDeviceIpv4Addr(unittest.TestCase):
    """DeviceIpv4Addr unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
