# coding: utf-8

# flake8: noqa

"""
    Device Status

    Device Status can provide updates on the device's connectivity state  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from devicestatus_client.api_client import ApiClient

# import Configuration
from devicestatus_client.configuration import Configuration

# import exceptions
from devicestatus_client.exceptions import OpenApiException
from devicestatus_client.exceptions import ApiAttributeError
from devicestatus_client.exceptions import ApiTypeError
from devicestatus_client.exceptions import ApiValueError
from devicestatus_client.exceptions import ApiKeyError
from devicestatus_client.exceptions import ApiException
