# coding: utf-8

"""
    QoS

    QoS manages communication bandwidth for a given device.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.as_session_with_qo_s_subscription import AsSessionWithQoSSubscription
from openapi_client import configuration


class TestAsSessionWithQoSSubscription(unittest.TestCase):
    """AsSessionWithQoSSubscription unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
