# coding: utf-8

"""
    Location

    Location can verify if the specified user is within the given area  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from location_client import schemas  # noqa: F401


class Location(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def point() -> typing.Type['GeographicalCoordinates']:
                return GeographicalCoordinates
        
            @staticmethod
            def civicAddress() -> typing.Type['CivicAddress']:
                return CivicAddress
            __annotations__ = {
                "point": point,
                "civicAddress": civicAddress,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["point"]) -> 'GeographicalCoordinates': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["civicAddress"]) -> 'CivicAddress': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["point", "civicAddress", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["point"]) -> typing.Union['GeographicalCoordinates', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["civicAddress"]) -> typing.Union['CivicAddress', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["point", "civicAddress", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        point: typing.Union['GeographicalCoordinates', schemas.Unset] = schemas.unset,
        civicAddress: typing.Union['CivicAddress', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Location':
        return super().__new__(
            cls,
            *_args,
            point=point,
            civicAddress=civicAddress,
            _configuration=_configuration,
            **kwargs,
        )

from location_client.model.civic_address import CivicAddress
from location_client.model.geographical_coordinates import GeographicalCoordinates
