# coding: utf-8

"""
    Slice

    Slice management, creating and deleting network slices.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slice_client import schemas  # noqa: F401


class AdministrativeState(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "LOCKED": "LOCKED",
            "SHUTTING_DOWN": "SHUTTING_DOWN",
            "UNLOCKED": "UNLOCKED",
        }
    
    @schemas.classproperty
    def LOCKED(cls):
        return cls("LOCKED")
    
    @schemas.classproperty
    def SHUTTING_DOWN(cls):
        return cls("SHUTTING_DOWN")
    
    @schemas.classproperty
    def UNLOCKED(cls):
        return cls("UNLOCKED")
