# coding: utf-8

"""
    Slice

    Slice management, creating and deleting network slices.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slice_client import schemas  # noqa: F401


class SliceTypeName(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "eMBB": "E_MBB",
            "URLLC": "URLLC",
            "MIoT": "MIO_T",
        }
    
    @schemas.classproperty
    def E_MBB(cls):
        return cls("eMBB")
    
    @schemas.classproperty
    def URLLC(cls):
        return cls("URLLC")
    
    @schemas.classproperty
    def MIO_T(cls):
        return cls("MIoT")
