# coding: utf-8

"""
    Device Status

    Device Status can provide updates on the device's connectivity state  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from devicestatus_client.paths.connectivity.post import CreateConnectivitySubscription
from devicestatus_client.paths.event_subscriptions.post import CreateEventSubscription
from devicestatus_client.paths.connectivity_id.delete import DeleteConnectivity
from devicestatus_client.paths.event_subscriptions_id.delete import DeleteEventSubscription
from devicestatus_client.paths.connectivity_id.get import GetConnectivity
from devicestatus_client.paths.event_subscriptions_id.get import GetEventSubscription
from devicestatus_client.paths.connectivity_id.put import UpdateConnectivity


class DefaultApi(
    CreateConnectivitySubscription,
    CreateEventSubscription,
    DeleteConnectivity,
    DeleteEventSubscription,
    GetConnectivity,
    GetEventSubscription,
    UpdateConnectivity,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
